export const reservationChartData = [{
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}, {
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}, {
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}, {
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}, {
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}, {
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}, {
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}, {
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}, {
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}, {
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}, {
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}, {
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}, {
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}, {
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}, {
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}, {
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}, {
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}, {
    code: 'T12345',
    route: 'AHM - MUM Via Express Highway',
    time: '13:15 PM',
    sourceStation: 'Ahmedabad - CTM',
    destinationStation: 'Mumbai - Dadar',
    vehicleType: 'Non - AC',
    serviceType: 'Gurjar Nagri',
    seatType: 'Seater',
    vehicleNumber: 'GJ18 YY 1234',
    depotName: 'Depot 1',
    action: ''
}];
export const reservationChartHistoryData = [
    {
        code: '30/03/22',
        route: 'AMH - MUM',
        vehicleType: 'Non-AC',
        serviceType: 'Pink',
        seatType: 'Sleeper',
        createdOn: '15/04/22',
        createdBy: '15/04/22',
        action: ''
    },
    {
        code: '30/03/22',
        route: 'AMH - MUM',
        vehicleType: 'Non-AC',
        serviceType: 'Pink',
        seatType: 'Sleeper',
        createdOn: '15/04/22',
        createdBy: '15/04/22',
        action: ''
    },
    {
        code: '30/03/22',
        route: 'AMH - MUM',
        vehicleType: 'Non-AC',
        serviceType: 'Pink',
        seatType: 'Sleeper',
        createdOn: '15/04/22',
        createdBy: '15/04/22',
        action: ''
    },
    {
        code: '30/03/22',
        route: 'AMH - MUM',
        vehicleType: 'Non-AC',
        serviceType: 'Pink',
        seatType: 'Sleeper',
        createdOn: '15/04/22',
        createdBy: '15/04/22',
        action: ''
    },
    {
        code: '30/03/22',
        route: 'AMH - MUM',
        vehicleType: 'Non-AC',
        serviceType: 'Pink',
        seatType: 'Sleeper',
        createdOn: '15/04/22',
        createdBy: '15/04/22',
        action: ''
    },
    {
        code: '30/03/22',
        route: 'AMH - MUM',
        vehicleType: 'Non-AC',
        serviceType: 'Pink',
        seatType: 'Sleeper',
        createdOn: '15/04/22',
        createdBy: '15/04/22',
        action: ''
    },
    {
        code: '30/03/22',
        route: 'AMH - MUM',
        vehicleType: 'Non-AC',
        serviceType: 'Pink',
        seatType: 'Sleeper',
        createdOn: '15/04/22',
        createdBy: '15/04/22',
        action: ''
    },
];