export const pnrData = [{
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}, {
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}, {
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}, {
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}, {
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}, {
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}, {
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}, {
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}, {
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}, {
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}, {
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}, {
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}, {
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}, {
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}, {
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}, {
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}, {
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}, {
    pnrTicket: 'T12345',
    personName: 'Ajay Devgan',
    age: '55',
    gender: 'Male',
    contactNumber: '8574857481',
    journeyDate: '15/04/22 15:30 PM',
    boardingStation: 'Mumbai-Dadar',
    dropingStation: 'Mumbai-Dadar',
    fareCharges: '60',
    status: 'Paid',
    action: ''
}];